global using System.Text.Json;
global using Sefer.Backend.SharedConfig.Lib.Abstractions;
global using Sefer.Backend.SharedConfig.Lib.Models;
global using System.Text.Json.Serialization;
global using Sefer.Backend.SharedConfig.Lib.Config;
global using Sefer.Backend.SharedConfig.Lib.Providers;
global using System.Text.Json.Nodes;
global using Azure.Storage.Blobs;
global using System.Diagnostics.CodeAnalysis;